# Generated by Django 5.0 on 2023-12-08 13:30

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestsDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(default='+380', max_length=20, validators=[website.models.validate_number])),
                ('mail', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('time_of_receipt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
