# Generated by Django 5.0 on 2023-12-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequestsdatabase',
            old_name='mail',
            new_name='email',
        ),
    ]
